emotionForm/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.submitInitForm, name='submitInitForm'),
    path('final', views.submitFinalForm, name='submitFinalForm'),
    # path('outlets.html')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emotionForm.urls')),    
    path('auth/', include('rest_authtoken.urls')),
]

emotionForm/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.contrib.auth.models import User

import uuid
from django.utils.translation import ugettext_lazy as _
 

emotion_choices = [
    ('sDisagree', 'Strongly Disagree'),
    ('disagree', 'Disagree'),
    ('neutral', 'Neutral'),
    ('agree', 'Agree'),
    ('sAgree', 'Strongly Agree'),

]

scale_choices = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
]

system_choices = [
    ('listening', 'Music'),
    ('drawing', 'Art'),
]
class Initial(models.Model):
    happy = models.CharField(
        max_length = 200,
        choices = emotion_choices
    )
    sad = models.CharField(
        max_length = 200,
        choices = emotion_choices
    )
    tired = models.CharField(
        max_length = 200,
        choices=emotion_choices
    )
    jittery = models.CharField(
        max_length = 200,
        choices=emotion_choices, 
    )
    scale = models.CharField(
        max_length = 200,
        choices=scale_choices
    )

    interest = models.CharField(
        max_length = 200,
        choices=system_choices
    )

    user = models.CharField(max_length = 200, default='')
    chosen_system = models.CharField(max_length = 200, default='')



class Final(models.Model):
    happy = models.CharField(
        max_length = 200,
        choices = emotion_choices
    )
    sad = models.CharField(
        max_length = 200,
        choices = emotion_choices
    )
    tired = models.CharField(
        max_length = 200,
        choices=emotion_choices
    )
    jittery = models.CharField(
        max_length = 200,
        choices=emotion_choices, 
    )
    scale = models.CharField(
        max_length = 200,
        choices=scale_choices
    )
    
    feedback = models.CharField(
        max_length = 200,
        default = ''
        # required=False,
    )
    user = models.CharField(max_length = 200, default='')

# class InitialForm(ModelForm):
#     class Meta:         
#         model = Initial
#         fields = ['happy', 'sad', 'tired', 'jittery', 'scale', 'interest']

# class FinalForm(ModelForm):
#     class Meta:
#         model = Final
#         fields = ['happy', 'sad', 'tired', 'jittery', 'scale', 'feedback']

emotionForm/forms.py
from django.forms import ModelForm
from django import forms
from .models import Initial, Final

from django.utils.safestring import mark_safe

class HorizontalRadioRenderer(forms.RadioSelect):
   def render(self):
     return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

emotion_choices = [
    ('sDisagree', ''),
    ('disagree', ''),
    ('neutral', ''),
    ('agree', ''),
    ('sAgree', ''),

]

scale_choices = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
]

system_choices = [
    ('listening', 'Music'),
    ('drawing', 'Art'),
]

# class InitialForm(ModelForm):
#     class Meta:
#         model = Initial
#         fields = ['happy', 'sad', 'tired', 'jittery', 'scale', 'interest']

class MyRadioWidget(forms.RadioSelect):
    template_name = 'myradiowidget.html'
    renderer=HorizontalRadioRenderer

class initialForm(ModelForm):


    # action = forms.CharField(max_length=60, widget=forms.HiddenInput())
    happy = forms.ChoiceField(choices = emotion_choices, widget = MyRadioWidget)
    # ppy = forms.ChoiceField(choices = emotion_choices, widget=forms.RadioSelect(renderer=HorizontalRadioRenderer))
    # happy = forms.MultipleChoiceField(
    # required=True,
    # label='You feel happy / content',
    # widget=forms.RadioSelect,
    # choices = emotion_choices,
    # )
    sad = forms.ChoiceField(choices = emotion_choices, widget = MyRadioWidget)
    tired = forms.ChoiceField(choices = emotion_choices, widget = MyRadioWidget)
    jittery = forms.ChoiceField(choices = emotion_choices, widget = MyRadioWidget)
    scale = forms.ChoiceField(choices = scale_choices, widget = MyRadioWidget)
    interest = forms.ChoiceField(choices = system_choices, widget = MyRadioWidget)
    # token = 
    # interest = forms.ChoiceField(choices = system_choices, widget = forms.CheckboxSelectMultiple())


    class Meta:
        model = Initial
        fields = ('happy', 'sad', 'tired','jittery', 'scale', 'interest')

class finalForm(ModelForm):
    happy = forms.ChoiceField(choices = emotion_choices, widget = MyRadioWidget)
    sad = forms.ChoiceField(choices = emotion_choices, widget = MyRadioWidget)
    tired = forms.ChoiceField(choices = emotion_choices, widget = MyRadioWidget)
    jittery = forms.ChoiceField(choices = emotion_choices, widget = MyRadioWidget)
    scale = forms.ChoiceField(choices = scale_choices, widget = MyRadioWidget)
    feedback  = forms.CharField(required=False, label='If you would like, provide feedback on the website or any comments about your experience')
    # feedback = forms.CharField(
    #     required=False,
    #     label='If you would like, provide feedback on the website or any comments about your experience',
    # )
    class Meta:
        model = Final
        fields = ('happy', 'sad', 'tired','jittery', 'scale', 'feedback')



# class emotionsForm(initialForm, finalForm):
#     happy = forms.MultipleChoiceField(
#         required=True,
#         label='You feel happy / content',
#         widget=forms.RadioSelect,
#         choices = emotion_choices,
#     )
#     sad = forms.MultipleChoiceField(
#         required=True,
#         label='You feel sad / gloomy',
#         widget=forms.RadioSelect,
#         choices=emotion_choices,
#     )
#     tired = forms.MultipleChoiceField(
#         required=True,
#         label='You feel tired / drowsy',
#         widget=forms.RadioSelect,
#         choices=emotion_choices,
#     )
#     jittery = forms.MultipleChoiceField(
#         required=True,
#         label='You feel jittery / nervous',
#         widget=forms.RadioSelect,
#         choices=emotion_choices,
#     )
#     scale = forms.MultipleChoiceField(
#         required=True,
#         label='On a scale of 1 to 5, 1 being unpleasant and 5 being pleasant, how do you feel?',
#         widget=forms.RadioSelect,
#         choices=scale_choices,
#     )


# class interestForm(initialForm):
#     interest = forms.MultipleChoiceField(
#         required=True,
#         label='What creative outlet do you prefer?',
#         choices=system_choices,
#     )

# class feedbackForm(finalForm):
#     feedback = forms.CharField(
#         required=False,
#         label='If you would like, provide feedback on the website or any comments about your experience',
#     )

emotionForm/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .forms import initialForm, finalForm
from .models import Initial, Final

from django import forms
from django.db import models


from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.response import Response



# class CustomAuthToken(ObtainAuthToken):
#     def post(self, request, *args, **kwargs):
#         serializer = self.serializer_class(data=request.data,
#                                            context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         user = serializer.validated_data['user']
#         token, created = Token.objects.get_or_create(user=user)
#         return Response({
#             'token': token.key,
#         })

from rest_framework.authtoken.models import Token

import random
import uuid

uniqueID = uuid.uuid4()
def submitInitForm(request):
    # if this is a POST request we need to process the form data
    # form = initialForm()
    if request.method == 'POST':
        form = initialForm(request.POST or None)
        # create a form instance and populate it with data from the request:
        
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
                #replace w init form info
        # initialInfo.happy = form.cleaned_data['happy']
        # initialInfo.sad = form.cleaned_data['sad']
        # intialInfo.tired = form.cleaned_data['tired']
        # initialInfo.jittery = form.cleaned_data['jittery']
        # initialInfo.scale = form.cleaned_data['scale']
        # initialInfo.interest = form.cleaned_data['interest']
            # token = Token.objects.get_or_create(user=instance)
            # print(token.key)

            
        
        # initialInfo = form.save()
        # initialInfo.save()
            # fs = form.save(commit=False)
            choice = ''
            drawing_systems = ['http://weavesilk.com/', 'https://csh.bz/line/05xp.html', 'https://csh.bz/jsb/naquqo.html', 'https://csh.bz/jsb/garoqa.html']
            music_systems = ['https://semiconductor.withgoogle.com/', 'https://experiments.withgoogle.com/ai/ai-duet/view/', 'https://lab.hakim.se/radar/', 'https://www.patatap.com']
            interest = form.cleaned_data.get('interest')
            if interest == "drawing":
                choice = random.choice(drawing_systems)
                system = {"system_link": choice}
            elif interest == "listening":
                choice = random.choice(music_systems)
                system = {"system_link": choice}
            # fs.interest = models.CharField(max_length = 200)

            # def form_valid(self, form):
            #     self.object = form.save(commit=False)
            #     self.object.chosen_system = "choice"
            #     self.object.save()
            #     return super(ModelFormMixin, self).form_valid(form)
            form_instance = Initial.objects.create(happy = form.cleaned_data['happy'], sad = form.cleaned_data['sad'], tired = form.cleaned_data['tired'], jittery = form.cleaned_data['jittery'], scale = form.cleaned_data['scale'],chosen_system = choice, user = uniqueID)
            form_instance.save()

            # return cleaned_data
            
            # form.save()
            return render(request, "outlets.html", system)
        
            # i = Initial(happy=happy, sad=sad, tired=tired, jittery=jittery, scale=scale, interest=interest)
            # i.save()
            
            # initialInfo = form.save()


            

    # if a GET (or any other method) we'll create a blank form
    else:
        form = initialForm()


    return render(request, 'survey.html', {'form': form})


def submitFinalForm(request):
    # if this is a POST request we need to process the form data
    # form = initialForm()
    if request.method == 'POST':
        form = finalForm(request.POST or None)

        # create a form instance and populate it with data from the request:
        
        # check whether it's valid:
        if form.is_valid():
            form_instance = Final.objects.create(happy = form.cleaned_data['happy'], sad = form.cleaned_data['sad'], tired = form.cleaned_data['tired'], jittery = form.cleaned_data['jittery'], scale = form.cleaned_data['scale'],feedback = form.cleaned_data['feedback'], user = uniqueID)
            form_instance.save()
        


            return HttpResponseRedirect('/')


    # if a GET (or any other method) we'll create a blank form
    else:
        form = finalForm()


    return render(request, 'final.html', {'form': form})

emotionForm/templates/final.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
{% load static %}
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="{% static '/emotionForm/mystyle.css' %}">


<script src=""></script>
<head>
    <title>Final Survey</title>
</head>
<body>
<div id = "wrapper">
    <div class = "entireform">
    <div class = "header">
    <div class="header1">
    <h1>Thank you for taking part in our platform!</h1>
    <p>Please answer these questions so we can gage the effectiveness of co-creative systems.</p>
    </div>

    
</div>
<div class = "mainform">
    <form action="" method="post">
        <div class = "emotionquestions">
            <div class = "questions"> 
            <p class = "questiontext">You feel happy / content 😄😁 </p>
            <!-- <hr> -->
            <p class = "questiontext">You feel sad / gloomy 😞😔 </p>
            <!-- <hr> -->
            <p class = "questiontext">You feel tired / drowsy 😩😴 </p>
            <!-- <hr> -->
            <p class = "questiontext">You feel jittery / nervous 😅😬 </p>
            <!-- <hr> -->
            </div>
            
            <div class = "radiotext">
                <!-- <p>Strongly Disgaree</p> -->
                <div class = "radios">
                    <div class = "radiolabels">
                        <p class = "option">Strongly Disagree</p>
                        <p class = "option">Disagree</p>
                        <p class = "option">Neutral</p>
                        <p class = "option">Agree</p>
                        <p class = "option">Strongly Agree</p>
                    </div>
                    
                    {% csrf_token %}
                    <div class = radiobuttongroup>
                    <div class = "radiobutton">
                    {{ form.happy }}
                    </div>
                    <!-- <br>
                    <br> -->
                    <!-- <hr> -->
                    <div class = "radiobutton">
                        {{ form.sad }}
                    </div>
                    <!-- <hr> -->
                    <div class = "radiobutton">
                        {{ form.tired }}
                    </div>
                    <!-- <hr> -->
                    <div class = "radiobutton">
                        {{ form.jittery }}
                    </div>
                    </div>
                    <!-- <hr> -->
                </div>
            </div>
    </div>
        <div class = "remaining">
            <p class = "scaleQ">On a scale of 1 to 5, 1 being unpleasant and 5 being pleasant, how do you feel?</p>
            <div class = "scale">
                <!-- <button class="button-circle-bottom">1</button>               -->
                {{ form.scale}}
            </div>
            <div class = "feedback">
            <p>Any feedback? </p>
            {{ form.feedback }}
            </div>
        </div>
        {% block style %}
        <style>
        #help{
            text-align: center;
            width: 19%;
        }

        .radiobuttongroup input[type=radio]{
            border: 0px;
            width: 100%;
            height: 1.2em;
        }

        label[for=id_scale_0]{
        padding-right: 100px;
        border: 0px;
        width:100%;
        height: 5em;
        }
        label[for=id_scale_1]{
        padding-right: 100px;
        }
        label[for=id_scale_2]{
        padding-right: 100px;
        }
        label[for=id_scale_3]{
        padding-right: 100px;
        }
        label[for=id_scale_4]{
        padding-right: 100px;
        }

        label[for=id_interest_0]{
        padding-right: 100px;
        }
        label[for=id_interest_1]{
        padding-right: 100px;
        }

        input[value="sDisagree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="disagree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="neutral"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="agree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="sAgree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="sAgree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }

        input[value="1"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="2"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="3"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="4"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="5"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[id="id_feedback"]{
            width: 500px;
            border: 0; padding: 7px 0; border-bottom: 1px solid #ccc;
            outline: none;
        }

        /* input[id="id_feedback"] ~ .focus-border{position: relative; bottom: 0; left: 0; width: 0; height: 2px; background-color: #3399FF; transition: 0.4s;}
        input[id="id_feedback"]:focus ~ .focus-border{width: 100; transition: 0.4s;} */

        </style>
{% endblock %}
        <br>
        <div class = "submitbtn">
            <input type="submit" value="Submit" class="button btn">
        </div>
        <br>
        <br>
        <br>
        {% if form.errors %}
    <ol>
    {% for error in form.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}
    </form>

</div>
</div>
</div>
</body>
</html>

emotionForm/templates/myradiowidget.html
{% with id=widget.attrs.id %}<div{% if id %} id="{{ id }}" {% endif %}{% if widget.attrs.class %} class="{{ widget.attrs.class }}" {% endif %}>
    {% for group, options, index in widget.optgroups %}{% if group %}
    <div style='display:inline-block'>
        {{ group }}<div style='display:inline-block' {% if id %} id="{{ id }}_{{ index }}" {% endif %}>
            {% endif %}{% for option in options %}
            <div style='display:inline-block' id = "help">{% include option.template_name with widget=option %}</div>{% endfor %}{% if group %}
    </div></div>{% endif %}{% endfor %}
    </div>{% endwith %}

emotionForm/templates/outlets.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
{% load static %}
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="{% static '/emotionForm/mystyle.css' %}">
<style>

</style>

<head>
    <title>Co Creative System</title>
    <!-- <script src = "{% static '/emotionForm/timer.js' %}"></script> -->
</head>
<body>
    <div>
        <!-- <div id="myModal" class="modal">
            <div class="modal-content">
              <span class="close">&times;</span>
              <p>Would you like to try another system or take our exit survey?</p>
              <a href="choose.html"><button>Another System</button></a>
              <a href="exitsurvey.html"><button>Exit Survey</button></a>
            </div>

        </div> -->

        <!-- <div class = "submitbtn"> -->

            <a href=/final><button class="btn exitbtn">Exit</button></a>
        <!-- </div> -->
        <br>
        <br>
        <br>
        <div id="ten-countdown" class="timer">
        <!-- <script type="text/javascript" src="timer.js?v=1"></script> -->
        <script src = "{% static '/emotionForm/timer.js' %}"></script>
        </div>

        <embed src={{system_link}} style="width:1600px; height: 800px;">
    </div>
</body>

emotionForm/templates/survey.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
{% load static %}
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="{% static '/emotionForm/mystyle.css' %}">
<style>
</style>
<script src=""></script>
<head>
    <title>Initial Survey</title>
</head>
<body>
<div id = "wrapper">
<div class = "entireform">
<div class="header">
    <div class = "header1">
    <h1>Welcome to Co-Creative Systems!</h1>
    </div>
    <div class = header2>
        <p>Begin your journey to co-creativity by taking this initial survey so we can better compliment your current state. Learn more about how co-creativity can improve mood <a href="https://www.scienceopen.com/document_file/3c52dbad-6932-485a-a2fd-01c678fc4a93/ScienceOpen/422_Feldman.pdf">here</a></p> 
        
    </div>


    <div class = "resources">
        <div class = "rlabel">
        <p>Extra Resources: </p>
        </div>
        <div class = "actualresources">
        <table>
        <tr>
            <th><a href="http://www.ulifeline.org/scu/">ULifeline</a></th> 
            <th><a href="https://screener.ulifeline.org/?_ga=2.118145290.280716972.1614229601-2075168577.1614229601">ULifeline Screener</a></th>
        </tr>    
        <tr>
            <th><a href="https://www.scu.edu/cowell/resources/mental-wellness-resources/">SCU Provided Resources</a></th>
            <th><a href="https://www.scu.edu/cowell/counseling-and-psychological-services-caps/">SCU CAPS</a>
            </th> 
        </tr>  
        </table> 
        </div>
    </div>
</div>

<!--h2 class ="header">Please answer these questions for us to better compliment your needs?</h3> -->
<br>
<br>
<div class = "mainform">

    <form action="" method="post">
        <div class = "emotionquestions">
            <div class = "questions"> 
            <p class = "questiontext">You feel happy / content 😄😁 </p>
            <!-- <hr> -->
            <p class = "questiontext">You feel sad / gloomy 😞😔 </p>
            <!-- <hr> -->
            <p class = "questiontext">You feel tired / drowsy 😩😴 </p>
            <!-- <hr> -->
            <p class = "questiontext">You feel jittery / nervous 😅😬 </p>
            <!-- <hr> -->
            </div>
            
            <div class = "radiotext">
                <!-- <p>Strongly Disgaree</p> -->
                <div class = "radios">
                    <div class = "radiolabels">
                        <p class = "option">Strongly Disagree</p>
                        <p class = "option">Disagree</p>
                        <p class = "option">Neutral</p>
                        <p class = "option">Agree</p>
                        <p class = "option">Strongly Agree</p>
                    </div>
                    
                    {% csrf_token %}
                    <div class = radiobuttongroup>
                    <div class = "radiobutton">
                    {{ form.happy }}
                    </div>
                    <!-- <br>
                    <br> -->
                    <!-- <hr> -->
                    <div class = "radiobutton">
                        {{ form.sad }}
                    </div>
                    <!-- <hr> -->
                    <div class = "radiobutton">
                        {{ form.tired }}
                    </div>
                    <!-- <hr> -->
                    <div class = "radiobutton">
                        {{ form.jittery }}
                    </div>
                    </div>
                    <!-- <hr> -->
                </div>
            </div>
    </div>
        <div class = "remaining">
            <p class = "scaleQ">On a scale of 1 to 5, 1 being unpleasant and 5 being pleasant, how do you feel?</p>
            <div class = "scale">
                <!-- <button class="button-circle-bottom">1</button>               -->
                {{ form.scale}}
            </div>
            <p class = "outletQ">What creative outlet do you prefer?</p>

            <div class = "interestOp">
                
            {{ form.interest }}
            </div>
        </div>
        {% block style %}
        <style>
        #help{
            text-align: center;
            width: 19%;
        }
        /* input[type=radio] {
    border: 0px;
    width: 100%;
    height: 1.2em;
} */

        .radiobuttongroup input[type=radio]{
            border: 0px;
            width: 100%;
            height: 1.2em;
        }

        label[for=id_scale_0]{
        padding-right: 100px;
        /* transform: scale(1.5); */
        /* border: 0px;
        width:100%;
        height: 5em; */
        }
        label[for=id_scale_1]{
        padding-right: 100px;
        }
        label[for=id_scale_2]{
        padding-right: 100px;
        }
        label[for=id_scale_3]{
        padding-right: 100px;
        }
        label[for=id_scale_4]{
        padding-right: 100px;
        }

        label[for=id_interest_0]{
        padding-right: 100px;
        }
        label[for=id_interest_1]{
        padding-right: 100px;
        }

        input[value="sDisagree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="disagree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="neutral"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="agree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="sAgree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }
        input[value="sAgree"]:hover{
            color: black;
            transform: scale(1.5);
            /* width: 19%; */
        }

        input[value="1"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="2"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="3"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="4"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="5"]:hover{
            color: black;
            transform: scale(1.5);
        }

        input[value="listening"]:hover{
            color: black;
            transform: scale(1.5);
        }
        input[value="drawing"]:hover{
            color: black;
            transform: scale(1.5);
        }
        

        </style>
{% endblock %}
        <br>
        <div class = "submitbtn">
            <input type="submit" value="Submit" class="button btn">
        </div>
        <br>
        <br>
        <br>
        {% if form.errors %}
    <ol>
    {% for error in form.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
{% endif %}
    </form>

</div>
</div>
</div>

</body>
</html>